# Generated by Django 3.0.2 on 2020-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.TextField(max_length=5)),
                ('purchase_price', models.IntegerField()),
            ],
        ),
    ]
