# Generated by Django 3.0.2 on 2020-02-04 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='number_of_shares',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
