# Generated by Django 3.0.2 on 2020-02-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200204_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=10)),
                ('daily_high', models.TextField(max_length=10)),
                ('daily_low', models.TextField(max_length=10)),
                ('daily_open', models.TextField(max_length=10)),
                ('daily_close', models.TextField(max_length=10)),
                ('stock_volume', models.TextField(max_length=10)),
                ('daily_adj_close', models.TextField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Stock')),
            ],
        ),
    ]
