# Generated by Django 3.0.2 on 2020-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200214_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stock',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(to='portfolio.Stock'),
        ),
    ]
