# Generated by Django 3.0.3 on 2020-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200220_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='created',
            new_name='portfolioCreated',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='updated',
            new_name='portfolioUpdated',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created',
            new_name='stockCreated',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='daily_adj_close',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='daily_close',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='daily_high',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='daily_low',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='daily_open',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stock_volume',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated',
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_adj_close',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_close',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_high',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_low',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_open',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stockUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_volume',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
