# Generated by Django 3.0.3 on 2020-02-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20200226_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Stock'),
            preserve_default=False,
        ),
    ]
