# Generated by Django 3.0.3 on 2020-02-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20200227_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stock',
        ),
    ]
