# Generated by Django 3.0.3 on 2020-03-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20200304_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='created',
            new_name='stockCreated',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='updated',
            new_name='stockUpdated',
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_adj_close',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_close',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_high',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_low',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_open',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_volume',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(to='portfolio.Stock'),
        ),
    ]
